# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ums_control.proto\x12\x05greet\"\x10\n\x0eGetListRequest\"(\n\nDictionary\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x0fListOfDictReply\x12 \n\x05\x64icts\x18\x01 \x03(\x0b\x32\x11.greet.Dictionary2R\n\x0eUserManagement\x12@\n\x0fGetListOfReauth\x12\x15.greet.GetListRequest\x1a\x16.greet.ListOfDictReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ums_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETLISTREQUEST']._serialized_start=28
  _globals['_GETLISTREQUEST']._serialized_end=44
  _globals['_DICTIONARY']._serialized_start=46
  _globals['_DICTIONARY']._serialized_end=86
  _globals['_LISTOFDICTREPLY']._serialized_start=88
  _globals['_LISTOFDICTREPLY']._serialized_end=139
  _globals['_USERMANAGEMENT']._serialized_start=141
  _globals['_USERMANAGEMENT']._serialized_end=223
# @@protoc_insertion_point(module_scope)
