//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::role_user::Entity as RoleUser;
pub use super::roles::Entity as Roles;
pub use super::services::Entity as Services;
pub use super::sessions::Entity as Sessions;
pub use super::users::Entity as Users;
