from enum import Enum


class Permission(Enum):
    AUTHENTICATE = "AUTHENTICATE"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    RESET_PASSWORD = "RESET_PASSWORD"
    LOGOUT = "LOGOUT"
    REFRESH_TOKENS = "REFRESH_TOKENS"

    GET_USER = "GET_USER"
    GET_USER_FULL = "GET_USER_FULL"
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"

    GET_SELF = "GET_SELF"
    UPDATE_SELF = "UPDATE_SELF"
    DELETE_SELF = "DELETE_SELF"

    GET_ROLE = "GET_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    DELETE_ROLE = "DELETE_ROLE"
    CREATE_ROLE = "CREATE_ROLE"

    GET_SELF_SESSIONS = "GET_SELF_SESSIONS"
    DELETE_SELF_SESSION = "DELETE_SELF_SESSION"
    GET_USER_SESSIONS = "GET_USER_SESSIONS"
    DELETE_USER_SESSION = "DELETE_USER_SESSION"
