from enum import Enum


class AccessTags(Enum):
    CAN_AUTHENTICATE = "CAN_AUTHENTICATE"
    CAN_SEND_VERIFY_CODE = "CAN_SEND_VERIFY_CODE"
    CAN_VERIFY_EMAIL = "CAN_VERIFY_EMAIL"
    CAN_RESET_PASSWORD = "CAN_RESET_PASSWORD"
    CAN_CONFIRM_RESET_PASSWORD = "CAN_CONFIRM_RESET_PASSWORD"
    CAN_LOGOUT = "CAN_LOGOUT"
    CAN_REFRESH_TOKENS = "CAN_REFRESH_TOKENS"

    CAN_GET_USER = "CAN_GET_USER"
    CAN_GET_USER_FULL = "CAN_GET_USER_FULL"
    CAN_CREATE_USER = "CAN_CREATE_USER"
    CAN_UPDATE_USER = "CAN_UPDATE_USER"

    CAN_GET_SELF = "CAN_GET_SELF"
    CAN_UPDATE_SELF = "CAN_UPDATE_USER"
    CAN_DELETE_SELF = "CAN_DELETE_SELF"

    CAN_GET_ROLE = "CAN_GET_ROLE"
    CAN_UPDATE_ROLE = "CAN_UPDATE_ROLE"
    CAN_DELETE_ROLE = "CAN_DELETE_ROLE"
    CAN_CREATE_ROLE = "CAN_CREATE_ROLE"

    CAN_GET_SELF_SESSIONS = "CAN_GET_SELF_SESSIONS"
    CAN_DELETE_SELF_SESSION = "CAN_DELETE_SELF_SESSION"
    CAN_GET_USER_SESSIONS = "CAN_GET_USER_SESSIONS"
    CAN_DELETE_USER_SESSION = "CAN_DELETE_USER_SESSION"

